face_recognition/face_recognition/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve
from django.urls import re_path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('recognition.urls')),
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

face_recognition/recognition/urls.py
from django.urls import path
from . import views

app_name = 'recognition'

urlpatterns = [
    path('home', views.IndexView.as_view()),
    path('video_feed', views.video_feed_view(), name="video_feed"),
    path('recognition_video_feed/', views.recognition_video_feed(), name='recognition_video_feed'),
    path('add_face_data/', views.add_face_data, name='add_face_data'),
    path('train_face_data/', views.train_face_data, name='train_face_data'),
    path('video_index/', views.video_index, name='video_index'),
    path('video_feed/', views.video_feed, name='video_feed'),
    path('webcam_feed/', views.webcam_feed, name='webcam_feed'),
    path('mask_feed/', views.mask_feed, name='mask_feed'),
	path('livecam_feed/', views.livecam_feed, name='livecam_feed'),
]

face_recognition/templates/home.html
<html>
  <head>
    <title>Video Live Stream</title>
  </head>
  <body>
    <h1>Video Live Stream</h1>
    <!-- <img src="{% url 'recognition:video_feed' %}"> -->
    <!-- <img src="{% url 'recognition:webcam_feed' %}"> -->
    <!-- <img src="{% url 'recognition:mask_feed' %}"> -->
    <img src="{% url 'recognition:recognition_video_feed' %}"/>
    <!-- <img src="{% url 'recognition:livecam_feed' %}"> -->
    <div class="container">
      <a href="{% url 'recognition:add_face_data' %}"/>顔のデータを取り込む</a>
      <a href="{% url 'recognition:train_face_data' %}">顔を学習させる</a>
    </div>
  </body>
</html>

face_recognition/templates/index.html
<html>
  <head>
    <title>Video Live Stream</title>
  </head>
  <body>
    <h1>Video Live Stream</h1>
    <div>
        <div id="image_area">
            <img src="/video_feed"/>
        </div>
    </div>
  </body>
</html>